theme = ["hugo-debugprint", "hugo-atom-feed", "hugo-jf2", "hugo-search-fuse-js", "refined"]

# Default values of custom site.Params
[Params]
  # https://github.com/tummychow/lanyon-hugo/issues/2#issuecomment-253274278
  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  themecolorbase = "green" # Valid values: "red", "orange", "yellow", "green", "cyan", "blue", "magenta", "brown"

  # Set favicons to true only if the following files are present in the project assets/ dir:
  # - safari-pinned-tab.svg
  # - manifest.json
  # - favicon-16x16.png
  # - favicon-32x32.png
  # - apple-touch-icon.png
  favicons = false

  # These inline CSS files have to live in layouts/partials/.
  custom_inline_css = [ # Pygments Trac theme
                        # "css/trac_pygments.css"  # Needs pygmentsUseClasses to be true
                        # Chroma Trac theme
                        # "css/trac_chroma.css"    # Needs pygmentsUseClasses to be true
                        # Chroma GitHub theme
                        "css/github_chroma.css"    # Needs pygmentsUseClasses to be true
                        , "css/style.css"
                      ]

  css_lazy_load = false

  [Params.fontawesome]
    style = "fal" # Valid values: "fas" (Solid), "far" (Regular), "fal" (Light), "fab" (Brands)

  [Params.urls]
    refined = "https://gitlab.com/kaushalmodi/hugo-theme-refined"
    ox_hugo = "https://github.com/kaushalmodi/ox-hugo"
    hugo = "https://github.com/gohugoio/hugo"

  # [Params.prefetch]
  #   fonts = ["/fonts/libre-baskerville/2012/subset/LibreBaskerville-Regular.woff2",
  #            "/fonts/iosevka/1.14.1/subset/iosevka-ss08-regular.woff2",
  #            "/fonts/linux-libertine/5.3.0/subset/LinBiolinum_Rah.woff2",
  #            "/fonts/source-sans-pro/2.020R-ro-1.075R-it/subset/SourceSansPro-Regular.woff2"]
